### ISSUE TITLE
Add new architecture linux/riscv64

### ISSUE THREAD

**Issue by mrestivill** [docker-library/golang#476] opened 2023-07-17 15:22 UTC
Add new architecture risc V 64 bits linux/riscv64 like alpine --> linux/riscv64

**Comment by mrestivill** [comment] 2023-07-17 15:32
https://hub.docker.com/u/riscv64/ there is a base image https://hub.docker.com/r/riscv64/buildpack-deps

**Comment by tianon** [comment] 2023-07-19 18:49
Duplicate of https://github.com/docker-library/golang/issues/435 (which is still accurate).

(Having support on Debian Unstable is unfortunately insufficient - it's still not yet an official architecture supported by the Debian project, and having images based on Debian Unstable leads to a lot of not-unexpected instability both in our own builds and in the downstream builds of our users.)

**Closed by tianon** 2023-07-19 18:49 UTC
