### ISSUE TITLE
Alpine - install `make' by default?

### ISSUE THREAD

**Issue by VojtechVitek** [docker-library/golang#136] opened 2017-01-13 16:39 UTC
Lots of projects use Makefiles. Can we `apk add --update make` by default?

**Comment by tianon** [comment] 2017-01-13 17:32
This is a duplicate of https://github.com/docker-library/golang/issues/119.

See especially https://github.com/docker-library/golang/issues/119#issuecomment-266238703:

> For many/most users, it isn't necessary, and it cannot be removed after the fact, so we intentionally try to keep the Alpine image as slim as possible.
> 
> See also https://github.com/docker-library/docs/blob/7a1edc542ec7d17626ec5cee87e87ed99da71afb/golang/README.md#golangalpine, specifically:
> 
> > To minimize image size, it's uncommon for additional related tools (such as `git` or `bash`) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the [`alpine` image description](https://hub.docker.com/_/alpine/) for examples of how to install packages if you are unfamiliar). base, add the things you need in your own Dockerfile (see the [`alpine` image description](https://hub.docker.com/_/alpine/) for examples of how to install packages if you are unfamiliar).

**Closed by tianon** 2017-01-13 17:32 UTC
