### ISSUE TITLE
golang:1.10 mkdir /.cache/go-build/00: permission denied

### ISSUE THREAD

**Issue by wongoo** [docker-library/golang#225] opened 2018-06-08 09:19 UTC
FROM golang:1.10 will get the following error:

```
09:16:38 GOOS=linux go build -tags prod -ldflags='-w -s ' -o main
09:16:39 go: disabling cache (/.cache/go-build) due to initialization failure: mkdir /.cache/go-build/00: permission denied
```

**Comment by wglambert** [comment] 2018-06-08 16:39
Could you give all the commands you ran and any relevant contextual information or files for reproducing the issue

**Comment by wongoo** [comment] 2018-06-12 02:44
see [test project](https://github.com/wongoo/golang-jenkins-docker)

No error for directly running docker command:

```
docker run --rm \
  -w /go/src/$BASEDIR/$PROJECT \
  -v $(pwd):/go/src/$BASEDIR/$PROJECT \
  -it golang:1.10 \
  make build
```

The error occurs when running in jenkins:

```
docker.image('golang:1.10').inside {
  sh 'go version'
  sh 'pwd'
  sh 'env'
  sh 'mkdir -p $GOPATH/src/$BASEDIR; ln -sf `pwd` $GOPATH/src/$BASEDIR/$PROJECT'
  sh 'cd $GOPATH/src/$BASEDIR/* && make build'
}
```

**Comment by wongoo** [comment] 2018-06-15 09:33
create a jenkins issue here: https://issues.jenkins-ci.org/browse/JENKINS-51964

**Comment by yosifkit** [comment] 2018-06-19 20:57
Closing since it seems to be related to jenkins setup and not the golang image.

**Comment by zevdg** [comment] 2018-07-06 23:38
I'm not so sure this should be closed so fast.  This is pretty easy to reproduce without jenkens.  You just need try to build anything using the `-u` flag.

```
docker run -u $UID golang /bin/bash -c "cd /go/src/; mkdir hello; cd hello;
echo 'package main
import \"fmt\"
func main() {
    fmt.Println(\"hello world\")
}' > main.go; go run main.go"
```

The problem is that go assumes (not unreasonably) that you will have write access to $XDG_CACHE_HOME if it exists and `$HOME/.cache` if it does not
https://golang.org/src/cmd/go/internal/cache/default.go?s=2439:2657

It's even smart enough to turn off caching if $HOME=='', but unfortunately docker sets it to '/'
```
$ docker run -u $UID golang /bin/bash -c 'echo $HOME'
/
```

so go tries to mkdir `/.cache`  (actually `//.cache` but the double slash gets cleaned up somewhere) and fails because you aren't running as root anymore.

The fix is to set XDG_CACHE_HOME to something that is universally writable like `/tmp/.cache` or something like that.

Alternatively, this could be fixed upstream if go were to disable caching when $HOME=='/' like it does for $HOME==''.  I'll put in an issue to suggest it and see what they think.

**Comment by tianon** [comment] 2018-07-06 23:41
Good point and nice writeup, thanks; reopening.

**Comment by tianon** [comment] 2018-07-09 22:06
Just to follow up, the Go issue is at https://github.com/golang/go/issues/26280, appears to be favorable by upstream, and has a CL now at https://golang.org/cl/122487. :metal:

**Comment by tianon** [comment] 2018-07-09 22:07
(Closing, since this is going to be resolved directly upstream. :+1:)

**Closed by tianon** 2018-07-09 22:07 UTC
Labels: question

**Comment by Guilhermeslucas** [comment] 2019-09-10 13:39
Thanks a lot for the help, @zevdg . Works like a charm!
