### ISSUE TITLE
"go get" is broken in alpine image

### ISSUE THREAD

**Issue by avoskoboynik** [docker-library/golang#241] opened 2018-09-26 17:58 UTC
This makes alpine image useless for many tasks, including compiling/building.

Example:
```
alex ~> docker run -it --rm golang:1.11-alpine go get github.com/aws/aws-sdk-go
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/aws/aws-sdk-go: exec: "git": executable file not found in $PATH
alex ~> 
```

Same command works fine with standard image:
```
alex ~> docker run -it --rm golang:1.11 go get github.com/aws/aws-sdk-go
alex ~>                                                                                                                                                                                         
```

**Comment by tianon** [comment] 2018-09-26 18:01
Duplicate of #119, #140, #153, #157, #166, #198, #209, #230, #239.

**Closed by tianon** 2018-09-26 18:01 UTC
