### ISSUE TITLE
Plans to include dep in the official golang docker images?

### ISSUE THREAD

**Issue by deitch** [docker-library/golang#245] opened 2018-10-12 04:37 UTC
With dep the canonical way to manage and install dependencies, are there any plans to include it in the official library docker images of `golang`? Would be nice to be able to do:

```
docker run --rm -v $PWD:/go/src/<PATH> -w /go/src/<PATH> golang dep ensure -vendor-only
```

**Comment by JulienBreux** [comment] 2018-10-12 13:47
Really good question.

And very useful!

But, it's really hard because Go and Dep have different releases cycles.

**Comment by tianon** [comment] 2018-10-12 13:50
Duplicate of #204 

Also, Go 1.11 includes "Go Modules", which replace `dep`.

**Comment by deitch** [comment] 2018-10-12 13:51
> But, it's really hard because Go and Dep have different releases cycles.

Good point. It isn't the end of the world, since `dep` now is released as its own binary, I always can use a separate `dep` container

```
$ docker run --rm -v $PWD:/go/src/<PATH> -w /go/src/<PATH> some_dep_container dep ensure -vendor-only
$ docker run --rm -v $PWD:/go/src/<PATH> -w /go/src/<PATH> golang go build .
```

I guess we can live with it.

**Closed by tianon** 2018-10-12 13:50 UTC

**Comment by deitch** [comment] 2018-10-12 13:52
> Duplicate of #204

Dang. I searched in issues for `dep`, but never found it. Blame the search engine! :-)

Thanks
