### ISSUE TITLE
where is GOROOT

### ISSUE THREAD

**Issue by ORESoftware** [docker-library/golang#326] opened 2020-05-05 23:45 UTC
I have this:

```Dockerfile
FROM golang:1.13 as cm_base

USER root

RUN mkdir -p /tmp/cm-go-api
WORKDIR /tmp/cm-go-api

# debug env occasionally
RUN env | sort
```

I get this:

```shell
GOLANG_VERSION=1.13.8
GOPATH=/go
HOME=/root
HOSTNAME=1d2cd4c60f0c
PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/tmp/cm-go-api
```

is GOROOT supposed to be defined and if not, what is a good value for that so I can set it?

**Comment by tianon** [comment] 2020-05-05 23:49
Duplicate of #206:

> ```console
> $ docker run --rm golang:1.9 go env GOROOT
> /usr/local/go
> ```

**Closed by tianon** 2020-05-05 23:49 UTC
