### ISSUE TITLE
How to run a specific main

### ISSUE THREAD

**Issue by blacksails** [docker-library/golang#107] opened 2016-08-12 08:01 UTC
Im trying to use the go-wrapper to run a specific main file which is not in the root of my project. It seems that go-wrapper run takes for granted that the main file is located in the root of the project.

Will I need to run the binary in question manually, without the use of the go-wrapper?

**Comment by tianon** [comment] 2018-05-07 23:52
Sorry for the long delay -- your hunch was correct, and now that `go-wrapper` is deprecated and removed, the only way to do so.  In the past `go-wrapper` was intended to help folks get off the ground by auto-discovering the `main` package, but more complicated applications were always expected to graduate beyond `go-wrapper`.

Closing, since `go-wrapper` is now moot. :+1:

**Closed by tianon** 2018-05-07 23:52 UTC
Labels: question
