### ISSUE TITLE
golang:1.17.8 missing linux/arm64 architecture

### ISSUE THREAD

**Issue by howardjohn** [docker-library/golang#410] opened 2022-03-04 01:12 UTC
```
$ docker pull golang:1.17.8
1.17.8: Pulling from library/golang
no matching manifest for linux/amd64 in the manifest list entries
```

```
$ crane manifest golang:1.17.8 | jq '.. | .platform? | select(. !=null)' -c
{"architecture":"arm","os":"linux","variant":"v5"}
{"architecture":"386","os":"linux"}
{"architecture":"ppc64le","os":"linux"}
{"architecture":"s390x","os":"linux"}
{"architecture":"amd64","os":"windows","os.version":"10.0.20348.524"}
{"architecture":"amd64","os":"windows","os.version":"10.0.17763.2565"}


$ crane manifest golang:1.17.7 | jq '.. | .platform? | select(. !=null)' -c
{"architecture":"amd64","os":"linux"}
{"architecture":"arm","os":"linux","variant":"v5"}
{"architecture":"arm","os":"linux","variant":"v7"}
{"architecture":"arm64","os":"linux","variant":"v8"}
{"architecture":"386","os":"linux"}
{"architecture":"mips64le","os":"linux"}
{"architecture":"ppc64le","os":"linux"}
{"architecture":"s390x","os":"linux"}
{"architecture":"amd64","os":"windows","os.version":"10.0.20348.524"}
{"architecture":"amd64","os":"windows","os.version":"10.0.17763.2565"}
```

**Comment by tianon** [comment] 2022-03-04 01:15
Duplicate of #409

> https://github.com/docker-library/golang#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet
>
> (It's still building -- please be patient! :heart:)

**Closed by tianon** 2022-03-04 01:15 UTC
