### ISSUE TITLE
apt-get update && install use IPv6

### ISSUE THREAD

**Issue by rogierlommers** [docker-library/golang#45] opened 2015-03-26 08:44 UTC
We are using `golang:1.4.2-wheezy` for automatic building of go binaries. Unfortunately the machine which runs the container is not allowed to reach the www through IPv6. And apparently an `apt-get` command within the container uses IPv6 by default. Is it possible to change this? I have already tried to add `-o Acquire::ForceIPv4=true` to the apt-get command, but this does now work.

```
09:26:08 Step 1 : RUN apt-get -y update
09:26:08  ---> Running in 6d151ec1148b
09:27:12 Err http://http.debian.net wheezy Release.gpg
09:27:12   Cannot initiate the connection to http.debian.net:80 (2001:41c8:1000:21::21:35). - connect (101: Network is unreachable) [IP: 2001:41c8:1000:21::21:35 80]
```

**Comment by imrick** [comment] 2016-03-15 15:06
Hi,

We're running the same issue. We are using the latest jessie image and we're getting the following error:

Err http://httpredir.debian.org jessie Release.gpg
  Cannot initiate the connection to httpredir.debian.org:80 (2001:xxxx:xxxx:xx::xx:xx). - connect (101: Network is unreachable) [IP: 2001:xxxx:xxxx:xx::xx:xx 80]

I've also tried the "Acquire::ForceIPv4=true" apt configuration parameter but without any success. This is strange since the previous build of the image on the same host was a success ... .

If anyone has a solution.

Thanks

**Comment by imrick** [comment] 2016-03-23 11:04
We have solved our issue. In fact this is not related to IPV6 the message can be confusing. It was caused by a connectivity issue since the container does not have knowledge of the proxy on the build time (added by environment file in docker-compose.yml) add environment variables with the "args" attribute solved the issue.

If does help anyone ... .

**Comment by tianon** [comment] 2018-05-04 20:14
Closing, since this appears to be resolved (and was likely environmental or configuration-related). :+1:

**Closed by tianon** 2018-05-04 20:14 UTC
Labels: question
