### ISSUE TITLE
Missing gcc which is needed to make .test binaries. 

### ISSUE THREAD

**Issue by timothysc** [docker-library/golang#153] opened 2017-03-17 14:08 UTC
So gcc is needed to make test binaries, and I see in your Dockerfile that you delete it from a builddep dir.  

Use case: 
go test -i -c -o battery.test github.com/yaddayadda/pkg/battery

The standard golang container works ok, b/c the tooling is installed, but ideally I'd like to use the trim'd alpine containers.

**Comment by yosifkit** [comment] 2017-03-17 22:35
Basically a duplicate of #119; specifically https://github.com/docker-library/golang/issues/119#issuecomment-266238703:

> For many/most users, it isn't necessary, and it cannot be removed after the fact, so we intentionally try to keep the Alpine image as slim as possible.
> 
> See also https://github.com/docker-library/docs/blob/7a1edc542ec7d17626ec5cee87e87ed99da71afb/golang/README.md#golangalpine, specifically:
> 
> > To minimize image size, it's uncommon for additional related tools (such as `git` or `bash`) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the [`alpine` image description](https://hub.docker.com/_/alpine/) for examples of how to install packages if you are unfamiliar). base, add the things you need in your own Dockerfile (see the [`alpine` image description](https://hub.docker.com/_/alpine/) for examples of how to install packages if you are unfamiliar).

**Comment by timothysc** [comment] 2017-03-17 22:57
I disagree with the size vs. usefulness constraint on language/build containers.  For runtime containers that makes perfect sense, but this is a language/tooling container.  Also, there is not parity in tools needed across the different golang containers.

**Comment by khezen** [comment] 2018-08-28 13:54
`For many/most users, it isn't necessary, and it cannot be removed after the fact, so we intentionally try to keep the Alpine image as slim as possible.`

**Comment by tianon** [comment] 2019-01-22 02:21
See also https://github.com/docker-library/golang/issues/250#issuecomment-451201761, especially:

> I think our image description should probably link directly to https://github.com/golang/go/issues/19938 -- to summarize that thread's current state, Alpine is not actually an officially supported target for the maintainers of Go (it's non-trivial enough to get the test suite passing on Alpine that we're coming up on two years since it was first attempted in earnest).
>
> The reason this is relevant here is that ... I'm afraid it will lend more to the appearance of Alpine being something not only supported, but potentially even recommended by the Go team, which is definitely not accurate (and if we had a clean way to de-emphasize our *current* Alpine variants until that issue is resolved and upstream officially supports it, I would definitely be considering it).

**Comment by lily-lee** [comment] 2019-02-22 03:36
```
Step 8/8 : RUN gcc -v
 ---> Running in aa48abe03357
/bin/sh: gcc: not found
```

**Comment by goku321** [comment] 2020-01-06 10:23
I am using `golang:alpine` as my docker image(`go` version `1.13.5`) and there's no `gcc`. I had to install it manually.

**Comment by Freyert** [comment] 2020-06-23 19:28
Doing a `RUN apk add build-base` adds about 207 MB to alpine so you're not really that much better off using it.

It makes more sense to build using a more well supported distro and just copying into the slim version of that distro. Debian's slim distro is typically around 27MB which is less than the `golang` version because believe it or not `golang` is a pretty big install.

**Closed** 2020-06-23 21:29 UTC
Labels: Request
