### ISSUE TITLE
go build fails to read vcs info when .git is owned by a different user

### ISSUE THREAD

**Issue by forsaken628** [docker-library/golang#452] opened 2023-02-06 08:30 UTC
golang:bullseye built-in install git(2.30.2) which break our CI/CD system.

https://github.com/golang/go/issues/53532

**Comment by TeddiO** [comment] 2023-02-06 11:34
Can confirm a similar issue in our CI/CD pipelines. In addition if you run `go build` with the `-v` flag you get the extra output:

```
fatal: detected dubious ownership in repository at '/__w/<path>'
To add an exception for this directory, call:

	git config --global --add safe.directory /__w/<path>
```

1.19.4 and previous are functioning as intended .

**Comment by peterdeme** [comment] 2023-02-06 13:15
The interesting thing is that `actions/checkout@v3` even adds the current directory to the safe directories by default.

But for some reason it doesn't work. If you manually add it, it starts to work.

```yaml
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set workspace as safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
```

**Comment by sozercan** [comment] 2023-02-06 23:30
Looks like this is due to git update that backports CVE fixes in debian bullseye to 1:2.30.2-1+deb11u1
https://release.debian.org/proposed-updates/bullseye_diffs/git_2.30.2-1+deb11u1.debdiff

**Comment by tianon** [comment] 2023-02-08 21:34
The best solution here is probably going to be using `git config --add safe.directory /...` to your CI/builds :disappointed:

**Comment by yosifkit** [comment] 2023-02-08 22:06
Closing as this is not something we can work around generally and safely in the image and is the result of a CVE fix in `git`.

**Closed by yosifkit** 2023-02-08 22:06 UTC
